 
#include <cstdlib>
#include <iostream>
#include <math.h>

using namespace std;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


int main() 
{ 
    int num1 = 1; //previous number in fibonacci sequence
    int num2 = 2; //current number in fibonacci sequence
	int num3 = 0; // dummy used to rename the values once the next value is found
	int sum=2; // keeps running total of the sum of values
    while(num2 < 4000000)
    {
		num3=num2;
		num2=num3+num1; // write the new largest term in Fib sequence
		num1=num3; //write the old largest to the new second largest
		if(num2 % 2 == 0) // tests divisibility by 2
		{
			sum=sum+num2;
		}
		   	
	}
	cout <<"Sum of values: "<< sum << endl;
	system("PAUSE");
	return 0;
}
